name       : libpanel
version    : 1.2.0
release    : 3
source     :
    - https://download.gnome.org/sources/libpanel/1.2/libpanel-1.2.0.tar.xz : d9055bbbab9625f3f5ce6d1fd7132eb6ea34a6ba07a87e9938901fb8b31581e2
license    : LGPL-2.1-or-later
component  : programming.library
summary    : A dock/panel library for GTK 4
description: |
    Libpanel helps you create IDE-like applications using GTK 4 and libadwaita. It has widgets for panels, docks, columns and grids of pages. Primarily, it's design and implementation focus around GNOME Builder and Drafting projects.
builddeps  :
    - pkgconfig(gtk4)
    - pkgconfig(libadwaita-1)
    - vala
setup      : |
    %meson_configure -Ddocs=disabled
build      : |
    %ninja_build
install    : |
    %ninja_install
